### ISSUE TITLE
Affichage du login menu web

### ISSUE THREAD

**Issue by mathben** [AdminTL/gestion_personnage_TL#12]
On désire que les informations de types publiques soient accessibles à tout le public sans authentification.

Une personne peut accéder à la page de personnage, mais on lui demandera de s'authentifier s'il veut accéder à sa feuille de personnage ou s'il veut s'en créer une.
Le login va permettre aussi d'accéder à ses informations personnels et d'autre information pas encore défini (genre, choix du repas!)

**Comment by mathben** [comment]
En lien avec  : https://github.com/AdminTL/gestion_personnage_TL/issues/3

**Comment by mathben** [comment]
Blocked by #3

**Comment by Avasam** [comment]
Connexion/inscription côté serveur et client terminé: https://github.com/Avasam/gestion_personnage_TL/commits/user_authentification_%233

`@tornado.web.authenticated` pour automatiquement rediriger un utilisateur s'il n'est pas connecté.
`get_current_user()` identifie l'utilisateur présent par son cookie (user_id) et retourne un utilisateur.

À utiliser dans les Handlers (dans les pages HTML, juste enlever le `self.`):
`self.current_user` pour obtenir toutes les infos sur l'utilisateur connecté. 
`self.current_user.get("permission")` pour obtenir le niveau de permission.
`self.current_user.get(value)` pour obtenir toute autre info sur l'utilisateur courrant.

**Comment by mathben** [comment]
L'affichage de la page login est bonne, on peut accéder aussi à la page de profil.
La tâche sera terminé lorsqu'on pourra accéder à sa fiche à partir de sa page de profil ou du bouton Personnage dans le menu.

**Comment by mathben** [comment]
Done, on peut maintenant accéder à la fiche de personnage depuis son authentification.
