### ISSUE TITLE
create user management with authentification

### ISSUE THREAD

**Issue by mathben** [AdminTL/gestion_personnage_TL#3]
Need authentification with permission in client/server side.

We want homemade authentification + google auth + facebook auth + twitter auth.

Edit : we begin implementation with userapp, but development stopped, so we need to do our own implementation.

**Comment by mathben** [comment]
We try first implementation manually, but we prefer to use external library for more security and performance.
We try to use userapp https://www.userapp.io/
It works with tornado python and angularjs.
I did a fix in tornado : https://github.com/mathben/userapp-tornado

**Comment by mathben** [comment]
We are blocked now because the client side cannot keep the information when the user connect to userapp. Need to find the problem with angularjs.
I think the problem is about ng-router

**Comment by mathben** [comment]
Server side with python tornado : 
id of userapp, can be move in config file : https://github.com/AdminTL/gestion_personnage_TL/blob/ddb_controler_view/src/web/user.py
permission manage in handlers : https://github.com/AdminTL/gestion_personnage_TL/blob/ddb_controler_view/src/web/handlers.py
And here to setup all request : https://github.com/AdminTL/gestion_personnage_TL/blob/ddb_controler_view/src/web/base_handler.py

Client side with angularjs : 
angularjs service : https://github.com/AdminTL/gestion_personnage_TL/blob/ddb_controler_view/src/web/static/local/js/tl_ctrl.js
html login : https://github.com/AdminTL/gestion_personnage_TL/blob/ddb_controler_view/src/web/templates/login.html

Common usage between tornado and angularjs on base html page : https://github.com/AdminTL/gestion_personnage_TL/blob/ddb_controler_view/src/web/templates/_base.html

We don't want to show admin in html if no permission.

**Comment by mathben** [comment]
Tornado support with userapp
https://github.com/userapp-io/userapp-tornado
This version not support new version of tornado.

Angularjs
https://github.com/userapp-io/userapp-angular

Example with tornado and angularjs
https://github.com/userapp-io/tempbox-python-angularjs

**Comment by mathben** [comment]
New suggested documentation : 
* http://stackoverflow.com/questions/23592606/how-to-combine-tornado-authentication-and-angularjs
* https://thinkster.io/tutorials/angularjs-jwt-auth

**Comment by Avasam** [comment]
Working on it, without UserApp, see [WIP login branch](https://github.com/Avasam/gestion_personnage_TL/commits/login)
Good tornadoweb documentation : http://www.tornadoweb.org/en/stable/guide/security.html

**Comment by mathben** [comment]
Note, erase branch auth_control when task will be done.
auth_control use userapp. Maybe we can fork the project because somebody maybe want to continue this code.

**Comment by mathben** [comment]
@Avasam work on this task.

**Comment by Avasam** [comment]
User auth (from [this branch](https://github.com/Avasam/gestion_personnage_TL/tree/user_authentification_%233)) is now functionnal, but incomplete.

1 Move the password+salt elsewhere, outside of the user database.
2. Login/register errors should appear client side (eg: the user should be notified when trying to create an account with a username that already exists)
3. Client-side hash+salt (using username/mail for salt)
4. Password verification (to avoid typos when signing up)
5. Email verification link

Requires a profile page:
6. Let the user change email (includes email verification)
7. Let the user change password (includes changing salt)

8. "Forgot password?" button (Requires 5 to send an email and 7 to change password)

**Comment by Avasam** [comment]
Facebook/G+/Twitter auth: [Third party authentication](http://www.tornadoweb.org/en/stable/guide/security.html#third-party-authentication)
XSRF: [Cross-site request forgery protection](http://www.tornadoweb.org/en/stable/guide/security.html#cross-site-request-forgery-protection)

**Comment by mathben** [comment]
- documentation how to connect to google oauth2
- documentation how to connect to facebook oauth2
Ignore twitter authentification.
- add documentation how generate good password
Example : more than 8 caracters, not the same password of your email, not a dictionnary word, better with number and ponctuation character.
- Don't force the user to follow good password indication.
- Fix comment from this pull request : https://github.com/AdminTL/gestion_personnage_TL/pull/71/files#diff-a49633f5b2c7136afd0a70414fb0239fR153

**Comment by mathben** [comment]
- Need to test with arg "use_internet_static"
- Need to test in debug and normal run
- Need to test character page with and without authentification.

**Comment by mathben** [comment]
- Need a configuration file with host and port, configured in server side, when need to redirect page.

**Comment by mathben** [comment]
- Missing Cross-site request forgery protection : http://www.tornadoweb.org/en/stable/guide/security.html#cross-site-request-forgery-protection

**Comment by mathben** [comment]
- Doc google. To generate secret key, read : https://developers.google.com/identity/protocols/OAuth2ServiceAccount

**Comment by mathben** [comment]
- Write documentation to generate file auth.json with key from code
```
settings["google_oauth"]: auth_keys.get("google_oauth")
settings["facebook_api_key"]: auth_keys.get("facebook_api_key")
settings["facebook_secret"]: auth_keys.get("facebook_secret")
settings["twitter_consumer_key"]: auth_keys.get("twitter_consumer_key")
settings["twitter_consumer_secret"]: auth_keys.get("twitter_consumer_secret")
```

**Comment by mathben** [comment]
- Missing tornado oauth2 documentation : http://www.tornadoweb.org/en/stable/auth.html

**Comment by mathben** [comment]
- Need documentation to add private privacy in website for facebook : https://termsfeed.com/blog/privacy-policy-url-facebook-app/

**Comment by mathben** [comment]
I test with google and facebook, it works.
- Caracter sheet is broken
- We cannot authentificate with facebook/google when another same name exist.
- Need more verbosity when click on "connect to Facebook/Google" and user create automatic.
