### ISSUE TITLE
Gérer les certificats ssl pour le https et auto-regen si n'en possède pas

### ISSUE THREAD

**Issue by mathben** [AdminTL/gestion_personnage_TL#63]
Si l'application demande au démarrage d'utiliser le https, faire la génération du certificat de manière sécuritaire et informer que le certificat n'a pas été validé.
Utilisé le certificat donné par l'utilisateur. Noté lorsque le certificat change dans la base de donnée, envoyer courriel si c'est le cas aux administrateurs.

**Comment by mathben** [comment]
Faire aussi une redirection automatique du http vers https
https://github.com/tornadoweb/tornado/issues/523

**Comment by Avasam** [comment]
Le code pour créer le certificat est surement à changer, mais de mémoire le site se met automatiquement en HTTPS si on fait un certificat (voir dernière ligne, toutes les redirections utilisant le chemin absolut seront correctes):
/src/web/web.py
```
ssl_options = None
    if parse_arg.ssl:
        # use https if active ssl, secure http
        if not os.path.isfile(CERT_FILE_SSL) or not os.path.isfile(KEY_FILE_SSL):
            # Generate a self-signed certificate and key if we don't already have one.
            cmd = 'openssl req -x509 -sha256 -newkey rsa:2048 -keyout %s -out %s -days 36500 -nodes -subj' % (
                KEY_FILE_SSL, CERT_FILE_SSL)
            cmd_in = cmd.split() + ["/C=CA/ST=QC/L=Montreal/O=Traitre-lame/OU=gn.qc.ca"]

            subprocess.call(cmd_in)

        ssl_options = {"certfile": CERT_FILE_SSL, "keyfile": KEY_FILE_SSL}

    url = "http{2}://{0}:{1}".format(parse_arg.listen.address, parse_arg.listen.port, "s" if ssl_options else "")
```

**Comment by mathben** [comment]
Cette tâche vient de régler cette tâche-ci.
https://github.com/AdminTL/gestion_personnage_TL/issues/64
