### ISSUE TITLE
Obtenir nouveau certificat valide ssl pour le site

### ISSUE THREAD

**Issue by mathben** [AdminTL/gestion_personnage_TL#64]
Il faut trouver un certificat SSL pour le logiciel en production pour le moment qu'on va gérer la communication de l'authentification et autre entre le client et le serveur.

Il a des endroits qu'on peut en obtenir des gratuits, semble-t-il?

**Comment by Avasam** [comment]
Un certificat gratuit est un certificat "self-signed". Sinon un certificat "reconnu" c'est un certificat où tu payes une compagnie, détenteurs de ton certificat, pour que les navigateurs ait confiance immédiatement (vue que le certificat est signé d'une compagnie connue).

Le seul désavantage d'un certificat "self-signed" bien fait est que les navigateurs ne lui feront pas automatiquement confiance (l'utilisateur doit accepter ou importer le certificat, ce qui est d'ailleurs impossible à faire sur le navigateur par défaut d'android).

Tant que le certificat ne sera pas validé par le navigateur, le site sera **considéré** aussi insécure qu'un site http et l'utilisateur ne verra pas de petit cadenas vert à cçoté de l'url
![Cadenas SSL](http://puu.sh/uP7fo/bb760b427e.png)

**Comment by mathben** [comment]
Merci pour ces informations.
Je vais regarder pour https://gethttpsforfree.com/ 

Note que la tâche fait référence ici au site [www.traitrelame.ca](http://www.traitrelame.ca)

**Comment by gboudrias** [comment]
J'utilise dehydrated (un client Let's Encrypt) sur tous nos serveurs: https://github.com/lukas2511/dehydrated

C'est le plus simple que j'ai trouvé.

**Comment by mathben** [comment]
Ça fonctionne! Ça génère des certificats en exécutant un script!
Je vais retester une dernière fois demain avant de merger.
